//in this file we'll define actions labels that will perform action
// THESE ARE LABELS THAT WILL PERFORM ACTION and this msg will be sent to redux
// THESE ARE ALL ACTION TYPES 
// SPECIFIES THE TYPE OF ACTION WE HAVE TO PERFORM

export const ALL_RESTAURANTS_REQUEST = "ALL_RESTAURANTS_REQUEST";
export const ALL_RESTAURANTS_SUCCESS = "ALL_RESTAURANTS_SUCCESS";
export const ALL_RESTAURANTS_FAIL = "ALL_RESTAURANTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SORT_BY_REVIEWS = "SORT_BY_REVIEWS";
export const SORT_BY_RATINGS = "SORT_BY_RATINGS";
export const TOGGLE_VEG_ONLY = "TOGGLE_VEG_ONLY";